// Code generated by the Encore 1.48.8 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly ai: ai.ServiceClient
    public readonly analytics: analytics.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly bus: bus.ServiceClient
    public readonly data: data.ServiceClient
    public readonly geofencing: geofencing.ServiceClient
    public readonly incident: incident.ServiceClient
    public readonly location: location.ServiceClient
    public readonly notification: notification.ServiceClient
    public readonly user: user.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.ai = new ai.ServiceClient(base)
        this.analytics = new analytics.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.bus = new bus.ServiceClient(base)
        this.data = new data.ServiceClient(base)
        this.geofencing = new geofencing.ServiceClient(base)
        this.incident = new incident.ServiceClient(base)
        this.location = new location.ServiceClient(base)
        this.notification = new notification.ServiceClient(base)
        this.user = new user.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { optimizeRoute as api_ai_optimize_route_optimizeRoute } from "~backend/ai/optimize_route";
import { predictETA as api_ai_predict_eta_predictETA } from "~backend/ai/predict_eta";

export namespace ai {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.optimizeRoute = this.optimizeRoute.bind(this)
            this.predictETA = this.predictETA.bind(this)
        }

        /**
         * Analyzes and suggests route optimizations using AI.
         */
        public async optimizeRoute(params: RequestType<typeof api_ai_optimize_route_optimizeRoute>): Promise<ResponseType<typeof api_ai_optimize_route_optimizeRoute>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/optimize-route`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_optimize_route_optimizeRoute>
        }

        /**
         * Predicts ETA for a bus to reach a specific location using AI analysis.
         */
        public async predictETA(params: RequestType<typeof api_ai_predict_eta_predictETA>): Promise<ResponseType<typeof api_ai_predict_eta_predictETA>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/predict-eta`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_predict_eta_predictETA>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getPerformanceReport as api_analytics_get_performance_report_getPerformanceReport } from "~backend/analytics/get_performance_report";
import { recordMetric as api_analytics_record_metric_recordMetric } from "~backend/analytics/record_metric";

export namespace analytics {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getPerformanceReport = this.getPerformanceReport.bind(this)
            this.recordMetric = this.recordMetric.bind(this)
        }

        /**
         * Generates a performance report for buses, routes, drivers, or the entire system.
         */
        public async getPerformanceReport(params: RequestType<typeof api_analytics_get_performance_report_getPerformanceReport>): Promise<ResponseType<typeof api_analytics_get_performance_report_getPerformanceReport>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                endDate:    params.endDate,
                entityId:   params.entityId === undefined ? undefined : String(params.entityId),
                entityType: String(params.entityType),
                startDate:  params.startDate,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/performance`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_get_performance_report_getPerformanceReport>
        }

        /**
         * Records a performance metric for analysis.
         */
        public async recordMetric(params: RequestType<typeof api_analytics_record_metric_recordMetric>): Promise<ResponseType<typeof api_analytics_record_metric_recordMetric>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/metrics`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_record_metric_recordMetric>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { checkPermission as api_auth_check_permission_checkPermission } from "~backend/auth/check_permission";
import { login as api_auth_login_login } from "~backend/auth/login";
import { logout as api_auth_logout_logout } from "~backend/auth/logout";
import { signup as api_auth_signup_signup } from "~backend/auth/signup";
import { verifySession as api_auth_verify_session_verifySession } from "~backend/auth/verify_session";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.checkPermission = this.checkPermission.bind(this)
            this.login = this.login.bind(this)
            this.logout = this.logout.bind(this)
            this.signup = this.signup.bind(this)
            this.verifySession = this.verifySession.bind(this)
        }

        /**
         * Checks if a user has permission to perform an action on a resource.
         */
        public async checkPermission(params: RequestType<typeof api_auth_check_permission_checkPermission>): Promise<ResponseType<typeof api_auth_check_permission_checkPermission>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/check-permission`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_check_permission_checkPermission>
        }

        /**
         * Authenticates a user and creates a session.
         */
        public async login(params: RequestType<typeof api_auth_login_login>): Promise<ResponseType<typeof api_auth_login_login>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_login_login>
        }

        /**
         * Logs out a user by invalidating their session.
         */
        public async logout(params: RequestType<typeof api_auth_logout_logout>): Promise<ResponseType<typeof api_auth_logout_logout>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/logout`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_logout_logout>
        }

        /**
         * Creates a new user account and logs them in.
         */
        public async signup(params: RequestType<typeof api_auth_signup_signup>): Promise<ResponseType<typeof api_auth_signup_signup>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/signup`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_signup_signup>
        }

        /**
         * Verifies a session token and returns user information.
         */
        public async verifySession(params: RequestType<typeof api_auth_verify_session_verifySession>): Promise<ResponseType<typeof api_auth_verify_session_verifySession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/verify`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_verify_session_verifySession>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { addBusStop as api_bus_add_bus_stop_addBusStop } from "~backend/bus/add_bus_stop";
import { createBus as api_bus_create_bus_createBus } from "~backend/bus/create_bus";
import { createRoute as api_bus_create_route_createRoute } from "~backend/bus/create_route";
import { getRouteStops as api_bus_get_route_stops_getRouteStops } from "~backend/bus/get_route_stops";
import { listBuses as api_bus_list_buses_listBuses } from "~backend/bus/list_buses";
import { listRoutes as api_bus_list_routes_listRoutes } from "~backend/bus/list_routes";

export namespace bus {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addBusStop = this.addBusStop.bind(this)
            this.createBus = this.createBus.bind(this)
            this.createRoute = this.createRoute.bind(this)
            this.getRouteStops = this.getRouteStops.bind(this)
            this.listBuses = this.listBuses.bind(this)
            this.listRoutes = this.listRoutes.bind(this)
        }

        /**
         * Adds a bus stop to a route.
         */
        public async addBusStop(params: RequestType<typeof api_bus_add_bus_stop_addBusStop>): Promise<ResponseType<typeof api_bus_add_bus_stop_addBusStop>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/routes/stops`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bus_add_bus_stop_addBusStop>
        }

        /**
         * Creates a new bus in the fleet.
         */
        public async createBus(params: RequestType<typeof api_bus_create_bus_createBus>): Promise<ResponseType<typeof api_bus_create_bus_createBus>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/buses`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bus_create_bus_createBus>
        }

        /**
         * Creates a new bus route.
         */
        public async createRoute(params: RequestType<typeof api_bus_create_route_createRoute>): Promise<ResponseType<typeof api_bus_create_route_createRoute>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/routes`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bus_create_route_createRoute>
        }

        /**
         * Retrieves all stops for a specific route.
         */
        public async getRouteStops(params: { routeId: number }): Promise<ResponseType<typeof api_bus_get_route_stops_getRouteStops>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/routes/${encodeURIComponent(params.routeId)}/stops`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bus_get_route_stops_getRouteStops>
        }

        /**
         * Retrieves all buses in the fleet.
         */
        public async listBuses(): Promise<ResponseType<typeof api_bus_list_buses_listBuses>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/buses`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bus_list_buses_listBuses>
        }

        /**
         * Retrieves all bus routes with stop counts.
         */
        public async listRoutes(): Promise<ResponseType<typeof api_bus_list_routes_listRoutes>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/routes`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bus_list_routes_listRoutes>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { seedData as api_data_seed_data_seedData } from "~backend/data/seed_data";

export namespace data {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.seedData = this.seedData.bind(this)
        }

        /**
         * Seeds the database with sample data for testing.
         */
        public async seedData(): Promise<ResponseType<typeof api_data_seed_data_seedData>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_data_seed_data_seedData>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { checkGeofence as api_geofencing_check_geofence_checkGeofence } from "~backend/geofencing/check_geofence";
import { createGeofence as api_geofencing_create_geofence_createGeofence } from "~backend/geofencing/create_geofence";

export namespace geofencing {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.checkGeofence = this.checkGeofence.bind(this)
            this.createGeofence = this.createGeofence.bind(this)
        }

        /**
         * Checks if a bus location triggers any geofence events.
         */
        public async checkGeofence(params: RequestType<typeof api_geofencing_check_geofence_checkGeofence>): Promise<ResponseType<typeof api_geofencing_check_geofence_checkGeofence>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/geofences/check`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_geofencing_check_geofence_checkGeofence>
        }

        /**
         * Creates a new geofence area.
         */
        public async createGeofence(params: RequestType<typeof api_geofencing_create_geofence_createGeofence>): Promise<ResponseType<typeof api_geofencing_create_geofence_createGeofence>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/geofences`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_geofencing_create_geofence_createGeofence>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { listIncidents as api_incident_list_incidents_listIncidents } from "~backend/incident/list_incidents";
import { reportIncident as api_incident_report_incident_reportIncident } from "~backend/incident/report_incident";
import { updateIncident as api_incident_update_incident_updateIncident } from "~backend/incident/update_incident";

export namespace incident {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.listIncidents = this.listIncidents.bind(this)
            this.reportIncident = this.reportIncident.bind(this)
            this.updateIncident = this.updateIncident.bind(this)
        }

        /**
         * Retrieves incidents with optional filtering.
         */
        public async listIncidents(params: RequestType<typeof api_incident_list_incidents_listIncidents>): Promise<ResponseType<typeof api_incident_list_incidents_listIncidents>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                busId:    params.busId === undefined ? undefined : String(params.busId),
                severity: params.severity,
                status:   params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/incidents`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_incident_list_incidents_listIncidents>
        }

        /**
         * Reports a new incident from a bus driver.
         */
        public async reportIncident(params: RequestType<typeof api_incident_report_incident_reportIncident>): Promise<ResponseType<typeof api_incident_report_incident_reportIncident>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/incidents`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_incident_report_incident_reportIncident>
        }

        /**
         * Updates an incident status or details.
         */
        public async updateIncident(params: RequestType<typeof api_incident_update_incident_updateIncident>): Promise<ResponseType<typeof api_incident_update_incident_updateIncident>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description: params.description,
                status:      params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/incidents/${encodeURIComponent(params.incidentId)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_incident_update_incident_updateIncident>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getBusLocation as api_location_get_bus_location_getBusLocation } from "~backend/location/get_bus_location";
import { listAllLocations as api_location_list_all_locations_listAllLocations } from "~backend/location/list_all_locations";
import { updateLocation as api_location_update_location_updateLocation } from "~backend/location/update_location";

export namespace location {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getBusLocation = this.getBusLocation.bind(this)
            this.listAllLocations = this.listAllLocations.bind(this)
            this.updateLocation = this.updateLocation.bind(this)
        }

        /**
         * Retrieves the current location and status of a bus.
         */
        public async getBusLocation(params: { busId: number }): Promise<ResponseType<typeof api_location_get_bus_location_getBusLocation>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/location/bus/${encodeURIComponent(params.busId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_location_get_bus_location_getBusLocation>
        }

        /**
         * Retrieves current locations of all active buses.
         */
        public async listAllLocations(): Promise<ResponseType<typeof api_location_list_all_locations_listAllLocations>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/location/all`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_location_list_all_locations_listAllLocations>
        }

        /**
         * Updates the real-time location of a bus and checks for geofence events.
         */
        public async updateLocation(params: RequestType<typeof api_location_update_location_updateLocation>): Promise<ResponseType<typeof api_location_update_location_updateLocation>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/location/update`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_location_update_location_updateLocation>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { listNotifications as api_notification_list_notifications_listNotifications } from "~backend/notification/list_notifications";
import { markAsRead as api_notification_mark_as_read_markAsRead } from "~backend/notification/mark_as_read";
import { sendNotification as api_notification_send_notification_sendNotification } from "~backend/notification/send_notification";
import { updatePreferences as api_notification_update_preferences_updatePreferences } from "~backend/notification/update_preferences";

export namespace notification {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.listNotifications = this.listNotifications.bind(this)
            this.markAsRead = this.markAsRead.bind(this)
            this.sendNotification = this.sendNotification.bind(this)
            this.updatePreferences = this.updatePreferences.bind(this)
        }

        /**
         * Retrieves all notifications for a user.
         */
        public async listNotifications(params: { userId: number }): Promise<ResponseType<typeof api_notification_list_notifications_listNotifications>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/user/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notification_list_notifications_listNotifications>
        }

        /**
         * Marks a notification as read.
         */
        public async markAsRead(params: { notificationId: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/notifications/${encodeURIComponent(params.notificationId)}/read`, {method: "PUT", body: undefined})
        }

        /**
         * Sends a notification to a user.
         */
        public async sendNotification(params: RequestType<typeof api_notification_send_notification_sendNotification>): Promise<ResponseType<typeof api_notification_send_notification_sendNotification>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/send`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notification_send_notification_sendNotification>
        }

        /**
         * Updates notification preferences for a user.
         */
        public async updatePreferences(params: RequestType<typeof api_notification_update_preferences_updatePreferences>): Promise<ResponseType<typeof api_notification_update_preferences_updatePreferences>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/preferences`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notification_update_preferences_updatePreferences>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { addChild as api_user_add_child_addChild } from "~backend/user/add_child";
import { createUser as api_user_create_user_createUser } from "~backend/user/create_user";
import { getUser as api_user_get_user_getUser } from "~backend/user/get_user";
import { listChildren as api_user_list_children_listChildren } from "~backend/user/list_children";
import { topUpWallet as api_user_top_up_wallet_topUpWallet } from "~backend/user/top_up_wallet";
import { updateUser as api_user_update_user_updateUser } from "~backend/user/update_user";

export namespace user {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addChild = this.addChild.bind(this)
            this.createUser = this.createUser.bind(this)
            this.getUser = this.getUser.bind(this)
            this.listChildren = this.listChildren.bind(this)
            this.topUpWallet = this.topUpWallet.bind(this)
            this.updateUser = this.updateUser.bind(this)
        }

        /**
         * Adds a child to a parent's account.
         */
        public async addChild(params: RequestType<typeof api_user_add_child_addChild>): Promise<ResponseType<typeof api_user_add_child_addChild>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/children`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_add_child_addChild>
        }

        /**
         * Creates a new user in the system.
         */
        public async createUser(params: RequestType<typeof api_user_create_user_createUser>): Promise<ResponseType<typeof api_user_create_user_createUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_create_user_createUser>
        }

        /**
         * Retrieves a user by their ID.
         */
        public async getUser(params: { id: number }): Promise<ResponseType<typeof api_user_get_user_getUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_get_user_getUser>
        }

        /**
         * Retrieves all children for a parent.
         */
        public async listChildren(params: { parentId: number }): Promise<ResponseType<typeof api_user_list_children_listChildren>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.parentId)}/children`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_list_children_listChildren>
        }

        /**
         * Tops up a user's digital wallet.
         */
        public async topUpWallet(params: RequestType<typeof api_user_top_up_wallet_topUpWallet>): Promise<ResponseType<typeof api_user_top_up_wallet_topUpWallet>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/wallet/topup`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_top_up_wallet_topUpWallet>
        }

        /**
         * Updates user profile information.
         */
        public async updateUser(params: RequestType<typeof api_user_update_user_updateUser>): Promise<ResponseType<typeof api_user_update_user_updateUser>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                email: params.email,
                name:  params.name,
                phone: params.phone,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_update_user_updateUser>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.8)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

const target = import.meta.env.VITE_ENCORE_API_URL || import.meta.env.VITE_CLIENT_TARGET || "https://school-run-bus-app-3iki.encr.app";
export default new Client(target, { requestInit: { credentials: "include" } });
